### PR TITLE
release 1.9.6

### PR DESCRIPTION
**Pull request by zhangjustin**
try to release new version 1.9.6 of zask

please review.

### CODE REVIEW

**Comment by tjoelsson** [comment]
I think you can edit the release instead of creating a new one

**Comment by zhangjustin** [comment]
need this PR , because i need to publish to pypi

**Comment by zhangjustin** [comment]
please review.

**Review by tjoelsson — APPROVED** [review]

**Review by mark-juwai — APPROVED** [review]

**Comment by zhangjustin** [comment]
thanks guys.

**Pull request merged**
