### PR TITLE
upgrade sqlalchemy version to 1.2.8

### PR DESCRIPTION
**Pull request by zhangjustin**
## Summary of changes

upgrade sqlalchemy version to 1.2.8
try to use sqlalchemy new features: `pool_pre_ping`

## How to Test

1. sqlachemy document:

http://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic

@tjoelsson @mark-juwai

### CODE REVIEW

**Comment by tjoelsson** [comment]
Do we have to increase the minimum version?

**Comment by zhangjustin** [comment]
now we use 1.1.11,  I think it's fine.

**Comment by zhangjustin** [comment]
updated, keep sqlalchemy minimum version.

**Comment by zhangjustin** [comment]
if you want to use feature `POOL_PRE_PING`, you must to use sqlalchemy `1.2.*`

**Comment by zhangjustin** [comment]
update, please review.

**Review by tjoelsson — APPROVED** [review]

**Comment by zhangjustin** [comment]
@mark-juwai , please review.

**Review by mark-juwai — APPROVED** [review]

**Pull request merged**
